name: shipment_merchent_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

#--------------- PACKAGES ------------------#
dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.6
  iconsax:

  # Utility Packages
  http:
  intl:
  logger:
  url_launcher:
  flutter_native_splash:
  smooth_page_indicator:
  lottie:
  sizer:
  pinput:
  animated_bottom_navigation_bar:
  percent_indicator:
  dartz:
  carousel_slider:
  image_picker:
  google_maps_flutter:
  searchfield:
  qr_code_scanner:
  flutter_launcher_icons:
  qr_flutter:
  shimmer:
  flutter_statusbarcolor_ns:
  cached_network_image:
  image_fade: ^0.6.2
  firebase_messaging: ^15.0.2
  firebase_core: ^3.1.1
  awesome_notifications:
  flutter_rating_bar:
  geolocator: ^12.0.0
  font_awesome_flutter: ^10.7.0
  package_info_plus: ^8.0.1
  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1
  shared_preferences:
  #--------------- ./ PACKAGES END ------------------#


  path: any
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/app_icon.png"


  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"

  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/images/
    - assets/gifs/

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 400
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-ExtraBold.ttf
          weight: 700

  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
